
# GRAFANA Dashboard server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: staging
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.3.1
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-provisioning
          configMap:
            name: grafana-dashboards-provisioning

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: staging
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
  type: NodePort

---

# LOKI - Log aggregation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: staging
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.6.3
          args:
            - "--pattern-ingester.enabled=true"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: staging
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP

---

# TEMPO - Distributed tracing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: staging
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.9.0
          args:
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3200
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: staging
spec:
  selector:
    app: tempo
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: jaeger-grpc
      protocol: TCP
      port: 14250
      targetPort: 14250
  type: ClusterIP

---

# MIMIR - Metrics storage (Prometheus compatible)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: staging
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.17.4
          args:
            - "-ingester.native-histograms-ingestion-enabled=true"
            - "-config.file=/etc/mimir.yaml"
          ports:
            - containerPort: 9009
              protocol: TCP
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir.yaml
              subPath: mimir.yaml
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-config

---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: staging
spec:
  selector:
    app: mimir
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
  type: ClusterIP

---

# PYROSCOPE - Continuous profiling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: staging
  labels:
    app: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
        - name: pyroscope
          image: grafana/pyroscope:1.16.2
          args:
            - "server"
          ports:
            - containerPort: 4040
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: staging
spec:
  selector:
    app: pyroscope
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
  type: ClusterIP

---
# =============================================================================
# ALLOY - Telemetry collector (OTLP)
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: staging
  labels:
    app: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.12.1
          args:
            - "run"
            - "--server.http.listen-addr=0.0.0.0:12345"
            - "--stability.level=public-preview"
            - "/etc/alloy/config.alloy"
          ports:
            - containerPort: 12345
              protocol: TCP
            - containerPort: 3100
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 12350
              protocol: TCP
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config

---
apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: staging
spec:
  selector:
    app: alloy
  ports:
    - name: http
      protocol: TCP
      port: 12345
      targetPort: 12345
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: pyroscope
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: faro
      protocol: TCP
      port: 12350
      targetPort: 12350
  type: ClusterIP

---
# CONFIGMAPS (Grafana-specific only - others created from files)
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: staging
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: false
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        isDefault: true
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        access: proxy
        url: http://pyroscope:4040

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provisioning
  namespace: staging
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards