apiVersion: v1
kind: Namespace
metadata:
  name: staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: staging
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      name: product-service
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: ORDER_SERVICE_ADDR
              value: "order-service:50051"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: staging
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: staging
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30008
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: staging
data:
  nginx.conf: | # Must match your Deployment's 'subPath'
    user nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    error_log /var/log/nginx/error.log;
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;
        location / {
          proxy_pass http://product-service:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
